setup:
	gcc -I"../install/include/" -L"../install/lib/" setup.c -lsoem -lpthread -lgsl -ldl -lgslcblas -lm -o setup_output

run_setup:
	sudo ./setup_output

run_debug_setup:
	sudo ./setup_output debug
	
clean:
	rm -f setup_output